# Generated by Django 4.2.5 on 2023-10-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='radio_choice',
            field=models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
