# Generated by Django 4.2.5 on 2023-10-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_radio_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='radio_choice',
        ),
        migrations.AddField(
            model_name='product',
            name='radio_choice1',
            field=models.CharField(choices=[('Ice', 'Option 1'), ('Cold', 'Option 2')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='radio_choice2',
            field=models.CharField(choices=[('Less Sweet', 'Option 1'), ('Normal Sweet', 'Option 2')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
