# Generated by Django 4.2.5 on 2023-10-03 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_product_radio_choice_product_radio_choice1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='radio_choice2',
            new_name='sweetness',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='radio_choice1',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
