# Generated by Django 4.2.5 on 2023-10-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_radio_choice2_product_sweetness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sweetness',
            field=models.CharField(choices=[('Less Sweet', 'Less Sweet'), ('Normal Sweet', 'Normal Sweet')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Cold', 'Cold'), ('Hot', 'Hot')], max_length=50),
        ),
    ]
